deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 0
  containers:
    - name: haproxy
      image:
        repository: haproxy
        tag: 2.9-alpine
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: plex
          containerPort: 32400
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 2000m
          memory: 2000Mi
      volumeMounts:
        - name: storage
          mountPath: /usr/local/etc/haproxy/
          subPath: haproxy/
  volumes:
    - name: storage
      type: pvc
      typeName: storage-pvc

infisicalSecrets:
  - name: infisical-certificates
    serviceTokenSecretName: service-token
    secretsPath: /certificates
    secretName: tls-secret
    secretType: kubernetes.io/tls

pvcs:
  - name: storage-pvc
    storageClassName: local-path-persistent
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem

services:
  - name: service
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
      - name: https
        protocol: TCP
        port: 443
      - name: plex
        protocol: TCP
        port: 32400
